name: naqla_driver
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

flutter_gen:
  output: lib/generated/flutter_gen/
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #? common state
  common_state:
    path: packages/common_state

  #?state management
  flutter_bloc: ^8.1.6
  dio: ^5.5.0+1

  #?UI
  flutter_screenutil: ^5.9.3
  text_scroll: ^0.2.0
  pinput: ^5.0.0
  dropdown_button2: ^2.3.9
  fluttertoast: ^8.2.6
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_spinkit: ^5.2.1
  iconly: ^1.0.1
  flutter_colorpicker: ^1.1.0
  modal_bottom_sheet: ^3.0.0
  badges: ^3.1.2

  #?image
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  image_cropper: ^7.1.0
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.3
  uuid: ^4.4.0
  http_parser: ^4.0.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  intl: ^0.19.0
  get_it: ^7.7.0
  injectable: ^2.4.2
  logger: ^2.3.0
  shared_preferences: ^2.2.3

  #?router
  go_router: ^14.2.0

  #?location:
  google_maps_flutter: ^2.7.0

  #?realTme
  socket_io_client: ^2.0.3+1


  flutter_localizations:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/jpg/logo.jpg"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.6.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1

flutter:

  uses-material-design: true
#  generate: true

  assets:
    - assets/images/svg/
    - assets/images/jpg/
    - assets/icons/essential/
    - assets/icons/png/
    - assets/icons/arrow/
    - assets/icons/flags/

  fonts:
    - family: noor
      fonts:
        - asset: assets/fonts/ArbFONTS-AGCRegular.ttf

flutter_intl:
  enabled: true

